[package]
name = "card_games"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[dependencies]
strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24"
rand = "0.8.5"
